---
abstract: 'Provide various analyses of Graphviz dot files'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.98
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GraphViz2-Marpa-PathUtils
provides:
  GraphViz2::Marpa::PathUtils:
    file: lib/GraphViz2/Marpa/PathUtils.pm
    version: 1.00
requires:
  Capture::Tiny: 0.1
  Date::Format: 2.24
  File::Which: 1.09
  GraphViz2::Marpa: 1.04
  Hash::FieldHash: 0.1
  IPC::Run3: 0.045
  Pod::Usage: 1.36
  Set::Array: 0.26
  Text::Xslate: 1.4001
  Tree: 1.01
  parent: 0.225
  strict: 1.03
  warnings: 1.03
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.00
